In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = './data/Kangaroo.csv'
kangaroo = pd.read_csv(data, sep = ',')
df_kangaroo = pd.DataFrame(kangaroo)

print(df_kangaroo)

       Unnamed: 0          id  \
0               0  20661494.0
1               1  20647642.0
2               2  20644816.0
3               3  20659813.0
4               4  20633249.0
...           ...         ...
80363      440319  20663057.0
80364      440364  20664347.0
80365      440966  20664354.0
80366      442237  20664377.0
80367      446550  20664387.0

                                                     url       type  \
0      https://www.immoweb.be/en/classified/apartment...  APARTMENT
1      https://www.immoweb.be/en/classified/house/for...      HOUSE
2      https://www.immoweb.be/en/classified/apartment...  APARTMENT
3      https://www.immoweb.be/en/classified/apartment...  APARTMENT
4      https://www.immoweb.be/en/classified/flat-stud...  APARTMENT
...                                                  ...        ...
80363  https://www.immoweb.be/en/classified/villa/for...      HOUSE
80364  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80365  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80366  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80367  https://www.immoweb.be/en/classified/apartment...  APARTMENT

           subtype  bedroomCount  bathroomCount         province  \
0        APARTMENT           2.0            1.0         Brussels
1            HOUSE           4.0            2.0         Brussels
2        APARTMENT           2.0            1.0         Brussels
3        APARTMENT           2.0            2.0         Brussels
4      FLAT_STUDIO           1.0            1.0         Brussels
...            ...           ...            ...              ...
80363        VILLA           3.0            1.0          Antwerp
80364    APARTMENT           3.0            1.0         Brussels
80365    APARTMENT           3.0            1.0  Flemish Brabant
80366    APARTMENT           3.0            2.0    West Flanders
80367    APARTMENT           3.0            2.0          Antwerp

                         locality  postCode  ...  hasOffice  toiletCount  \
0                       Etterbeek      1040  ...        NaN          1.0
1                       Etterbeek      1040  ...       True          3.0
2                       Etterbeek      1040  ...        NaN          1.0
3                       Bruxelles      1040  ...        NaN          2.0
4                       Etterbeek      1040  ...        NaN          1.0
...                           ...       ...  ...        ...          ...
80363                  Willebroek      2830  ...        NaN          3.0
80364                       Jette      1090  ...        NaN          1.0
80365  Grimbergen Strombeek-Bever      1853  ...        NaN          1.0
80366                    Westende      8434  ...        NaN          2.0
80367                     Wilrijk      2610  ...        NaN          2.0

       hasSwimmingPool hasFireplace hasTerrace terraceSurface  \
0                  NaN          NaN       True            7.0
1                  NaN          NaN       True            1.0
2                  NaN          NaN       True            2.0
3                  NaN          NaN       True            3.0
4                  NaN          NaN        NaN            NaN
...                ...          ...        ...            ...
80363             True          NaN       True            NaN
80364              NaN          NaN       True           10.0
80365              NaN          NaN       True            9.0
80366              NaN          NaN       True            NaN
80367              NaN          NaN       True            NaN

       terraceOrientation accessibleDisabledPeople epcScore     price
0                     NaN                      NaN        C  399000.0
1                     NaN                      NaN        E  895000.0
2                     NaN                      NaN        F  465000.0
3                     NaN                      NaN        B  590000.0
4                     NaN                      NaN        E  289000.0
...                   ...                      ...      ...       ...
80363                 NaN                      NaN        B  849000.0
80364                 NaN                      NaN        D  279000.0
80365                 NaN                      NaN        B  299000.0
80366                 NaN                      NaN        A  325000.0
80367                 NaN                      NaN        B  340000.0

[80368 rows x 53 columns]

1. Split Dataset : Data_test & Data_train

In [3]:
import random

# Choose 30% of dataset for test
df_30 = df_kangaroo.sample(frac=0.3, random_state=42)
print(df_30)
df_30.to_csv('data_fortest.csv', index=False)

       Unnamed: 0          id  \
38722      233522  20600265.0
63730      261126  11473882.0
61472      258494  20637182.0
21769      203861  20654571.0
40703      235710  11086014.0
...           ...         ...
54209      250349  20290532.0
25716      218757  11413471.0
2864         2873  20576812.0
26147      219229  20629815.0
52058      248091  20487906.0

                                                     url             type  \
38722  https://www.immoweb.be/en/classified/apartment...        APARTMENT
63730  https://www.immoweb.be/en/classified/duplex/fo...        APARTMENT
61472  https://www.immoweb.be/en/classified/apartment...        APARTMENT
21769  https://www.immoweb.be/en/classified/ground-fl...        APARTMENT
40703  https://www.immoweb.be/en/classified/penthouse...        APARTMENT
...                                                  ...              ...
54209  https://www.immoweb.be/en/classified/house/for...            HOUSE
25716  https://www.immoweb.be/en/classified/apartment...        APARTMENT
2864   https://www.immoweb.be/en/classified/new-real-...  APARTMENT_GROUP
26147  https://www.immoweb.be/en/classified/villa/for...            HOUSE
52058  https://www.immoweb.be/en/classified/house/for...            HOUSE

               subtype  bedroomCount  bathroomCount       province  \
38722        APARTMENT           1.0            1.0        Limburg
63730           DUPLEX           2.0            2.0  West Flanders
61472        APARTMENT           1.0            1.0  West Flanders
21769     GROUND_FLOOR           2.0            1.0        Antwerp
40703        PENTHOUSE           3.0            1.0          Li√®ge
...                ...           ...            ...            ...
54209            HOUSE          11.0            6.0        Hainaut
25716        APARTMENT           3.0            1.0        Antwerp
2864   APARTMENT_GROUP           NaN            NaN       Brussels
26147            VILLA           3.0            1.0        Antwerp
52058            HOUSE           5.0            2.0     Luxembourg

           locality  postCode  ...  hasOffice  toiletCount  hasSwimmingPool  \
38722          Peer      3990  ...        NaN          NaN              NaN
63730  Knokke-Heist      8300  ...        NaN          2.0              NaN
61472      Oostende      8400  ...        NaN          1.0              NaN
21769     ANTWERPEN      2020  ...        NaN          NaN              NaN
40703      Juprelle      4453  ...        NaN          2.0              NaN
...             ...       ...  ...        ...          ...              ...
54209   Ecaussinnes      7190  ...        NaN          5.0              NaN
25716     Antwerpen      2100  ...        NaN          NaN              NaN
2864        Ixelles      1050  ...        NaN          NaN              NaN
26147         Retie      2470  ...        NaN          2.0              NaN
52058         BANDE      6951  ...        NaN          3.0              NaN

      hasFireplace hasTerrace terraceSurface  terraceOrientation  \
38722          NaN       True            6.0                 NaN
63730          NaN       True            5.0                 NaN
61472          NaN        NaN            NaN                 NaN
21769          NaN       True           20.0                 NaN
40703          NaN       True            1.0               SOUTH
...            ...        ...            ...                 ...
54209          NaN        NaN            NaN                 NaN
25716          NaN       True           14.0                 NaN
2864           NaN        NaN            NaN                 NaN
26147          NaN       True            NaN                 NaN
52058          NaN       True            NaN                 NaN

      accessibleDisabledPeople epcScore     price
38722                      NaN      NaN  243050.0
63730                      NaN        C  795000.0
61472                      NaN        B  247000.0
21769                      NaN        B  475000.0
40703                      NaN        A  279000.0
...                        ...      ...       ...
54209                      NaN      NaN  299000.0
25716                      NaN        A  379000.0
2864                       NaN        A       NaN
26147                      NaN        B  675000.0
52058                      NaN        D  199000.0

[24110 rows x 53 columns]

In [4]:
# Collect the rest data for training
df_70 = df_kangaroo.drop(df_30.index)
print(df_70)
df_70.to_csv('data_fortrain.csv', index=False)

       Unnamed: 0          id  \
0               0  20661494.0
1               1  20647642.0
2               2  20644816.0
3               3  20659813.0
5               5  20639359.0
...           ...         ...
80362      380220  20379774.0
80363      440319  20663057.0
80365      440966  20664354.0
80366      442237  20664377.0
80367      446550  20664387.0

                                                     url       type  \
0      https://www.immoweb.be/en/classified/apartment...  APARTMENT
1      https://www.immoweb.be/en/classified/house/for...      HOUSE
2      https://www.immoweb.be/en/classified/apartment...  APARTMENT
3      https://www.immoweb.be/en/classified/apartment...  APARTMENT
5      https://www.immoweb.be/en/classified/apartment...  APARTMENT
...                                                  ...        ...
80362  https://www.immoweb.be/en/classified/house/for...      HOUSE
80363  https://www.immoweb.be/en/classified/villa/for...      HOUSE
80365  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80366  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80367  https://www.immoweb.be/en/classified/apartment...  APARTMENT

         subtype  bedroomCount  bathroomCount         province  \
0      APARTMENT           2.0            1.0         Brussels
1          HOUSE           4.0            2.0         Brussels
2      APARTMENT           2.0            1.0         Brussels
3      APARTMENT           2.0            2.0         Brussels
5      APARTMENT           2.0            1.0         Brussels
...          ...           ...            ...              ...
80362      HOUSE           4.0            2.0    East Flanders
80363      VILLA           3.0            1.0          Antwerp
80365  APARTMENT           3.0            1.0  Flemish Brabant
80366  APARTMENT           3.0            2.0    West Flanders
80367  APARTMENT           3.0            2.0          Antwerp

                         locality  postCode  ...  hasOffice  toiletCount  \
0                       Etterbeek      1040  ...        NaN          1.0
1                       Etterbeek      1040  ...       True          3.0
2                       Etterbeek      1040  ...        NaN          1.0
3                       Bruxelles      1040  ...        NaN          2.0
5                       ETTERBEEK      1040  ...        NaN          1.0
...                           ...       ...  ...        ...          ...
80362                    Maldegem      9990  ...        NaN          NaN
80363                  Willebroek      2830  ...        NaN          3.0
80365  Grimbergen Strombeek-Bever      1853  ...        NaN          1.0
80366                    Westende      8434  ...        NaN          2.0
80367                     Wilrijk      2610  ...        NaN          2.0

       hasSwimmingPool hasFireplace hasTerrace terraceSurface  \
0                  NaN          NaN       True            7.0
1                  NaN          NaN       True            1.0
2                  NaN          NaN       True            2.0
3                  NaN          NaN       True            3.0
5                  NaN          NaN       True            2.0
...                ...          ...        ...            ...
80362             True          NaN        NaN            NaN
80363             True          NaN       True            NaN
80365              NaN          NaN       True            9.0
80366              NaN          NaN       True            NaN
80367              NaN          NaN       True            NaN

       terraceOrientation accessibleDisabledPeople epcScore     price
0                     NaN                      NaN        C  399000.0
1                     NaN                      NaN        E  895000.0
2                     NaN                      NaN        F  465000.0
3                     NaN                      NaN        B  590000.0
5                     NaN                      NaN        D  375000.0
...                   ...                      ...      ...       ...
80362                 NaN                      NaN      NaN  649000.0
80363                 NaN                      NaN        B  849000.0
80365                 NaN                      NaN        B  299000.0
80366                 NaN                      NaN        A  325000.0
80367                 NaN                      NaN        B  340000.0

[56258 rows x 53 columns]

In [5]:
# Evaluate the missing values for df_30:
na_values = df_30.isnull().sum()
missing_percent = (na_values/ len(df_30)) * 100
print (missing_percent.round(2))
print(df_30.shape)

Unnamed: 0                    0.00
id                            0.00
url                           0.00
type                          0.00
subtype                       0.00
bedroomCount                  8.21
bathroomCount                17.00
province                      0.00
locality                      0.00
postCode                      0.00
habitableSurface             15.68
roomCount                    72.53
monthlyCost                 100.00
hasAttic                     84.13
hasBasement                  63.49
hasDressingRoom              96.84
diningRoomSurface            91.27
hasDiningRoom                82.21
buildingCondition            27.86
buildingConstructionYear     38.65
facedeCount                  33.70
floorCount                   53.68
streetFacadeWidth            80.57
hasLift                      76.60
floodZoneType                44.74
heatingType                  41.13
hasHeatPump                  90.79
hasPhotovoltaicPanels        89.82
hasThermicPanels             95.95
kitchenSurface               69.67
kitchenType                  48.11
landSurface                  50.36
hasLivingRoom                46.89
livingRoomSurface            64.18
hasBalcony                  100.00
hasGarden                    80.12
gardenSurface                80.12
gardenOrientation            92.87
parkingCountIndoor           64.37
parkingCountOutdoor          77.04
hasAirConditioning           98.59
hasArmoredDoor               95.66
hasVisiophone                80.90
hasOffice                    87.21
toiletCount                  31.35
hasSwimmingPool              97.74
hasFireplace                 96.03
hasTerrace                   40.60
terraceSurface               64.53
terraceOrientation           85.65
accessibleDisabledPeople    100.00
epcScore                     18.19
price                         4.88
dtype: float64
(24110, 53)

In [6]:
# Evaluate the missing values for df_70:
na_values = df_70.isnull().sum()
missing_percent = (na_values/ len(df_70)) * 100
print (missing_percent.round(2))
print(df_70.shape)

Unnamed: 0                    0.00
id                            0.00
url                           0.00
type                          0.00
subtype                       0.00
bedroomCount                  8.59
bathroomCount                17.06
province                      0.00
locality                      0.00
postCode                      0.00
habitableSurface             15.65
roomCount                    72.76
monthlyCost                 100.00
hasAttic                     84.55
hasBasement                  63.54
hasDressingRoom              96.68
diningRoomSurface            91.47
hasDiningRoom                82.49
buildingCondition            27.84
buildingConstructionYear     39.01
facedeCount                  33.78
floorCount                   53.11
streetFacadeWidth            80.76
hasLift                      76.18
floodZoneType                44.64
heatingType                  41.41
hasHeatPump                  90.66
hasPhotovoltaicPanels        90.06
hasThermicPanels             96.20
kitchenSurface               69.87
kitchenType                  47.73
landSurface                  50.99
hasLivingRoom                46.55
livingRoomSurface            63.89
hasBalcony                  100.00
hasGarden                    80.15
gardenSurface                80.15
gardenOrientation            93.10
parkingCountIndoor           65.08
parkingCountOutdoor          77.27
hasAirConditioning           98.60
hasArmoredDoor               95.29
hasVisiophone                79.76
hasOffice                    87.02
toiletCount                  31.49
hasSwimmingPool              97.74
hasFireplace                 96.29
hasTerrace                   41.15
terraceSurface               64.37
terraceOrientation           86.13
accessibleDisabledPeople    100.00
epcScore                     18.83
price                         5.02
dtype: float64
(56258, 53)